conditions: v1

matrix:
  include:
    - language: rust
      rust: stable
      env:
        - RUST_TESTS=true
    - language: python
      python: 3.6
      env:
        - PYTHON_TESTS=true
        - TOXENV=py36
    - if: branch = master
      language: python
      python: 3.7
        # cf https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true
      env:
        - PYTHON_TESTS=true
        - TOXENV=py37
    - if: branch = master
      language: python
      python: 3.8
        # cf https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true
      env:
        - PYTHON_TESTS=true
        - TOXENV=py38

before_install: . ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/test.sh

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
